SELECT 
    IDEMPRESA AS NK_EMPRESA,
    RAZAOSOCIAL AS DS_RAZAO_SOCIAL,
    C.DESCRCIDADE AS DS_NOME_CIDADE,
    C.UF DS_UF 
FROM PUBLIC.EMPRESA
    JOIN PUBLIC.CIDADE C ON C.IDCIDADE = EMPRESA.IDCIDADE